/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres';
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  uuid,
  varchar,
  type AnyPgColumn,
  numeric,
  boolean,
  timestamp,
  jsonb,
  serial,
  integer,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core';
import { sql, relations } from '@payloadcms/db-postgres/drizzle';
export const enum_categories_type = pgEnum('enum_categories_type', [
  'hidden',
  'displayed-all',
  'displayed-posts',
  'displayed-subcategories',
]);
export const enum_posts_status = pgEnum('enum_posts_status', ['published', 'draft']);

export const categories = pgTable(
  'categories',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    coverImage: uuid('cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug').notNull(),
    parent: uuid('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'set null',
    }),
    type: enum_categories_type('type').notNull().default('hidden'),
    weight: numeric('weight', { mode: 'number' }).notNull().default(0),
    seoTitle: varchar('seo_title'),
    seoDescription: varchar('seo_description'),
    ogImageMedia: uuid('og_image_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    noIndex: boolean('no_index').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('categories_cover_image_idx').on(columns.coverImage),
    index('categories_slug_idx').on(columns.slug),
    index('categories_parent_idx').on(columns.parent),
    index('categories_og_image_media_idx').on(columns.ogImageMedia),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ]
);

export const posts = pgTable(
  'posts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    category: uuid('category_id')
      .notNull()
      .references(() => categories.id, {
        onDelete: 'set null',
      }),
    teaser: varchar('teaser').notNull(),
    body: jsonb('body').notNull(),
    status: enum_posts_status('status').notNull().default('published'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    contentUpdatedAt: timestamp('content_updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    isFeatured: boolean('is_featured').default(false),
    seoTitle: varchar('seo_title'),
    seoDescription: varchar('seo_description'),
    ogImageMedia: uuid('og_image_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    noIndex: boolean('no_index').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('posts_slug_idx').on(columns.slug),
    index('posts_category_idx').on(columns.category),
    index('posts_published_at_idx').on(columns.publishedAt),
    index('posts_content_updated_at_idx').on(columns.contentUpdatedAt),
    index('posts_og_image_media_idx').on(columns.ogImageMedia),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
  ]
);

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    authorsID: uuid('authors_id'),
  },
  (columns) => [
    index('posts_rels_order_idx').on(columns.order),
    index('posts_rels_parent_idx').on(columns.parent),
    index('posts_rels_path_idx').on(columns.path),
    index('posts_rels_authors_id_idx').on(columns.authorsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: 'posts_rels_authors_fk',
    }).onDelete('cascade'),
  ]
);

export const static_contents = pgTable(
  'static_contents',
  {
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    body: jsonb('body').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('static_contents_updated_at_idx').on(columns.updatedAt),
    index('static_contents_created_at_idx').on(columns.createdAt),
  ]
);

export const configs = pgTable(
  'configs',
  {
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    value: varchar('value').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('configs_updated_at_idx').on(columns.updatedAt),
    index('configs_created_at_idx').on(columns.createdAt),
  ]
);

export const authors = pgTable(
  'authors',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    jobTitle: varchar('job_title').notNull(),
    bio: jsonb('bio').notNull(),
    avatarDark: uuid('avatar_dark_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    avatarDarkHovered: uuid('avatar_dark_hovered_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    avatarLight: uuid('avatar_light_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    avatarLightHovered: uuid('avatar_light_hovered_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    miniAvatar: uuid('mini_avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    githubUrl: varchar('github_url'),
    linkedinUrl: varchar('linkedin_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    uniqueIndex('authors_slug_idx').on(columns.slug),
    index('authors_avatar_dark_idx').on(columns.avatarDark),
    index('authors_avatar_dark_hovered_idx').on(columns.avatarDarkHovered),
    index('authors_avatar_light_idx').on(columns.avatarLight),
    index('authors_avatar_light_hovered_idx').on(columns.avatarLightHovered),
    index('authors_mini_avatar_idx').on(columns.miniAvatar),
    index('authors_updated_at_idx').on(columns.updatedAt),
    index('authors_created_at_idx').on(columns.createdAt),
  ]
);

export const media = pgTable(
  'media',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    alt: varchar('alt').notNull(),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ]
);

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ]
);

export const users = pgTable(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ]
);

export const payload_mcp_api_keys = pgTable(
  'payload_mcp_api_keys',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    label: varchar('label'),
    description: varchar('description'),
    posts_find: boolean('posts_find').default(false),
    posts_create: boolean('posts_create').default(false),
    posts_update: boolean('posts_update').default(false),
    posts_delete: boolean('posts_delete').default(false),
    categories_find: boolean('categories_find').default(false),
    categories_create: boolean('categories_create').default(false),
    categories_update: boolean('categories_update').default(false),
    categories_delete: boolean('categories_delete').default(false),
    authors_find: boolean('authors_find').default(false),
    authors_create: boolean('authors_create').default(false),
    authors_update: boolean('authors_update').default(false),
    authors_delete: boolean('authors_delete').default(false),
    staticContents_find: boolean('static_contents_find').default(false),
    staticContents_create: boolean('static_contents_create').default(false),
    staticContents_update: boolean('static_contents_update').default(false),
    staticContents_delete: boolean('static_contents_delete').default(false),
    configs_find: boolean('configs_find').default(false),
    configs_create: boolean('configs_create').default(false),
    configs_update: boolean('configs_update').default(false),
    configs_delete: boolean('configs_delete').default(false),
    media_find: boolean('media_find').default(false),
    media_create: boolean('media_create').default(false),
    media_update: boolean('media_update').default(false),
    media_delete: boolean('media_delete').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    enableAPIKey: boolean('enable_a_p_i_key'),
    apiKey: varchar('api_key'),
    apiKeyIndex: varchar('api_key_index'),
  },
  (columns) => [
    index('payload_mcp_api_keys_user_idx').on(columns.user),
    index('payload_mcp_api_keys_updated_at_idx').on(columns.updatedAt),
    index('payload_mcp_api_keys_created_at_idx').on(columns.createdAt),
  ]
);

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)]
);

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ]
);

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: uuid('categories_id'),
    postsID: uuid('posts_id'),
    'static-contentsID': varchar('static_contents_id'),
    configsID: varchar('configs_id'),
    authorsID: uuid('authors_id'),
    mediaID: uuid('media_id'),
    usersID: uuid('users_id'),
    'payload-mcp-api-keysID': uuid('payload_mcp_api_keys_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_static_contents_id_idx').on(columns['static-contentsID']),
    index('payload_locked_documents_rels_configs_id_idx').on(columns.configsID),
    index('payload_locked_documents_rels_authors_id_idx').on(columns.authorsID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_payload_mcp_api_keys_id_idx').on(columns['payload-mcp-api-keysID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['static-contentsID']],
      foreignColumns: [static_contents.id],
      name: 'payload_locked_documents_rels_static_contents_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['configsID']],
      foreignColumns: [configs.id],
      name: 'payload_locked_documents_rels_configs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: 'payload_locked_documents_rels_authors_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-mcp-api-keysID']],
      foreignColumns: [payload_mcp_api_keys.id],
      name: 'payload_locked_documents_rels_payload_mcp_api_keys_fk',
    }).onDelete('cascade'),
  ]
);

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ]
);

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
    'payload-mcp-api-keysID': uuid('payload_mcp_api_keys_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    index('payload_preferences_rels_payload_mcp_api_keys_id_idx').on(columns['payload-mcp-api-keysID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-mcp-api-keysID']],
      foreignColumns: [payload_mcp_api_keys.id],
      name: 'payload_preferences_rels_payload_mcp_api_keys_fk',
    }).onDelete('cascade'),
  ]
);

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ]
);

export const relations_categories = relations(categories, ({ one }) => ({
  coverImage: one(media, {
    fields: [categories.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
  ogImageMedia: one(media, {
    fields: [categories.ogImageMedia],
    references: [media.id],
    relationName: 'ogImageMedia',
  }),
}));
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  authorsID: one(authors, {
    fields: [posts_rels.authorsID],
    references: [authors.id],
    relationName: 'authors',
  }),
}));
export const relations_posts = relations(posts, ({ one, many }) => ({
  category: one(categories, {
    fields: [posts.category],
    references: [categories.id],
    relationName: 'category',
  }),
  ogImageMedia: one(media, {
    fields: [posts.ogImageMedia],
    references: [media.id],
    relationName: 'ogImageMedia',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}));
export const relations_static_contents = relations(static_contents, () => ({}));
export const relations_configs = relations(configs, () => ({}));
export const relations_authors = relations(authors, ({ one }) => ({
  avatarDark: one(media, {
    fields: [authors.avatarDark],
    references: [media.id],
    relationName: 'avatarDark',
  }),
  avatarDarkHovered: one(media, {
    fields: [authors.avatarDarkHovered],
    references: [media.id],
    relationName: 'avatarDarkHovered',
  }),
  avatarLight: one(media, {
    fields: [authors.avatarLight],
    references: [media.id],
    relationName: 'avatarLight',
  }),
  avatarLightHovered: one(media, {
    fields: [authors.avatarLightHovered],
    references: [media.id],
    relationName: 'avatarLightHovered',
  }),
  miniAvatar: one(media, {
    fields: [authors.miniAvatar],
    references: [media.id],
    relationName: 'miniAvatar',
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}));
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}));
export const relations_payload_mcp_api_keys = relations(payload_mcp_api_keys, ({ one }) => ({
  user: one(users, {
    fields: [payload_mcp_api_keys.user],
    references: [users.id],
    relationName: 'user',
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [payload_locked_documents_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  postsID: one(posts, {
    fields: [payload_locked_documents_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
  'static-contentsID': one(static_contents, {
    fields: [payload_locked_documents_rels['static-contentsID']],
    references: [static_contents.id],
    relationName: 'static-contents',
  }),
  configsID: one(configs, {
    fields: [payload_locked_documents_rels.configsID],
    references: [configs.id],
    relationName: 'configs',
  }),
  authorsID: one(authors, {
    fields: [payload_locked_documents_rels.authorsID],
    references: [authors.id],
    relationName: 'authors',
  }),
  mediaID: one(media, {
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
  usersID: one(users, {
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
  'payload-mcp-api-keysID': one(payload_mcp_api_keys, {
    fields: [payload_locked_documents_rels['payload-mcp-api-keysID']],
    references: [payload_mcp_api_keys.id],
    relationName: 'payload-mcp-api-keys',
  }),
}));
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
    relationName: '_rels',
  }),
}));
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
  'payload-mcp-api-keysID': one(payload_mcp_api_keys, {
    fields: [payload_preferences_rels['payload-mcp-api-keysID']],
    references: [payload_mcp_api_keys.id],
    relationName: 'payload-mcp-api-keys',
  }),
}));
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));

type DatabaseSchema = {
  enum_categories_type: typeof enum_categories_type;
  enum_posts_status: typeof enum_posts_status;
  categories: typeof categories;
  posts: typeof posts;
  posts_rels: typeof posts_rels;
  static_contents: typeof static_contents;
  configs: typeof configs;
  authors: typeof authors;
  media: typeof media;
  users_sessions: typeof users_sessions;
  users: typeof users;
  payload_mcp_api_keys: typeof payload_mcp_api_keys;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_categories: typeof relations_categories;
  relations_posts_rels: typeof relations_posts_rels;
  relations_posts: typeof relations_posts;
  relations_static_contents: typeof relations_static_contents;
  relations_configs: typeof relations_configs;
  relations_authors: typeof relations_authors;
  relations_media: typeof relations_media;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_payload_mcp_api_keys: typeof relations_payload_mcp_api_keys;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
